name: Sync BOM
on:
  push:
    branches:
      - main

# Use a personal token so that this action will trigger other actions (when the PR is created, all other checks are triggered)

jobs:
  sync-bom:
    name: Sync BOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build BOM
        run: |
          mvn --no-transfer-progress --activate-profiles update-bom clean install
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TNB_APP_APP_ID }}
          private_key: ${{ secrets.TNB_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: 'bom/pom.xml'
          commit-message: '[BOM] Sync BOM'
          branch: 'action-sync-bom'
          delete-branch: true
          title: 'Sync BOM'
          assignees: 'avano'
          author: 'GitHub Actions <actions@workflow.github.com>'

